pipeline {
    agent any

    stages {
        stage('Clone Git') {
            steps {
                sh 'rm -Rf linktoworld'
                sh 'rm -Rf linktoworld/container'
              //  sh 'mkdir terraform'
                sh 'git clone -b "devdoku" "https://${MY_TOKEN}@github.com/SUSIGUGH/linktoworld.git"'
                sh 'ls -ltr'
                sh 'mkdir linktoworld/container'
                sh 'mv linktoworld/mysql/* linktoworld/container/'
                sh 'ls -ltr linktoworld/container/'
            }
        }
      stage('Docker Build') {
            steps {
                  sh 'cd linktoworld/container/ && sudo docker build -t mysql .'
            }
           }
      stage('Docker Image Tag') {
            steps {
                  sh 'sudo docker image tag mysql susigugh/mysql:v1'
                  sh 'sudo docker image list'
            }
           }
        
        
    }
}
