pipeline {
    agent any

    stages {
        stage('Clone Git') {
            steps {
                sh 'rm -Rf linktoworld'
                sh 'rm -Rf linktoworld/container'
              //  sh 'mkdir terraform'
                sh 'git clone -b "devdoku" "https://${MY_TOKEN}@github.com/SUSIGUGH/linktoworld.git"'
                sh 'ls -ltr'
                sh 'mkdir linktoworld/container'
                sh 'mv linktoworld/mysql/* linktoworld/container/'
                sh 'ls -ltr linktoworld/container/'
            }
        }
      stage('Docker Build') {
            steps {
                  sh 'cd linktoworld/container/ && sudo docker build -t mysqlsusi01 .'
            }
           }
      stage('Docker Image Tag') {
            steps {
                  sh 'sudo docker image tag mysqlsusi01 docker.io/susigugh/mysqlsusi01:v1'
                  sh 'sudo docker image list'
            }
           }
             stage('Docker Push to Repo - Docker Hub') {
            steps {
                  sh 'sudo docker logout && sudo docker login -u${docker_user} -p${docker_password} && sudo docker push docker.io/susigugh/mysqlsusi01:v1'
            }
           } 
        
    }
}
